In [376]:
import numpy as np

In [377]:
X = np.array([
    [0, 0],
    [1, 0],
    [0, 1],
    [1, 1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0],
])

In [378]:
W1 = np.array([
    [0.2, 0.9],
    [-0.9, 0.8]
])

b1 = np.array([
    [-0.3],
    [0.2]
])

W2 = np.array([
    [-0.2, -0.9],
])

b2 = np.array([
    [0.7]
])

In [379]:
# Z1 = 0
# Z2 = 0
# D = 0

X1 = np.expand_dims(X[0], 0)
y1 = y[0]
h = W1 @ X1.T + b1
h

# kriva tanh formula na prezentaciji?
# y1 = np.tanh(h1) 
# [[-0.29131261],
#  [ 0.19737532]

H = 2/(1+np.exp(-h)) - 1
H

O = W2 @ H + b2
h, H, O

(array([[-0.3],
        [ 0.2]]),
 array([[-0.14888503],
        [ 0.09966799]]),
 array([[0.64007581]]))

In [380]:
dW2 = -(y1-O)*H.T
db2 = -(y1-O)
dW2, db2

(array([[-0.09529771,  0.06379507]]), array([[0.64007581]]))

In [381]:
dH = -(y1-O)*W2.T
dh = 0.5*(1-np.square(H))
dW1 = dH*dh*X1.T
db1 = dH*dh

In [382]:
W1 = W1 - 0.1*dW1
b1 = b1 - 0.1*db1
W2 = W2 - 0.1*dW2
b2 = b2 - 0.1*db2

print(f'Prvi par:\nIzlaz: {O.item():.4f}\n')
print(f'Sakriveni sloj težine: \n{W1}\nSakriveni sloj bias: \n{b1}\n')
print(f'Izlazni sloj težine: \n{W2}\nIzlazni sloj bias: \n{b2}')

Prvi par:
Izlaz: 0.6401

Sakriveni sloj težine: 
[[ 0.2  0.9]
 [-0.9  0.8]]
Sakriveni sloj bias: 
[[-0.29374113]
 [ 0.22851729]]

Izlazni sloj težine: 
[[-0.19047023 -0.90637951]]
Izlazni sloj bias: 
[[0.63599242]]


In [383]:
# Z1 = 1
# Z2 = 0
# D = 1

X2 = np.expand_dims(X[1], 0)
y2 = y[1]

h = W1 @ X2.T + b1
H = 2/(1+np.exp(-h)) - 1
O = W2 @ H + b2

dW2 = -(y2-O)*H.T
db2 = -(y2-O)

dH = -(y2-O)*W2.T
dh = 0.5*(1-np.square(H))
dW1 = dH*dh*X2.T
db1 = dH*dh

W1 = W1 - 0.1*dW1
b1 = b1 - 0.1*db1
W2 = W2 - 0.1*dW2
b2 = b2 - 0.1*db2

print(f'Drugi par:\nIzlaz: {O.item():.4f}\n')
print(f'Sakriveni sloj težine: \n{W1}\nSakriveni sloj bias: \n{b1}\n')
print(f'Izlazni sloj težine: \n{W2}\nIzlazni sloj bias: \n{b2}')

Drugi par:
Izlaz: 0.9383

Sakriveni sloj težine: 
[[ 0.19941351  0.89941351]
 [-0.9         0.8       ]]
Sakriveni sloj bias: 
[[-0.29432761]
 [ 0.22601328]]

Izlazni sloj težine: 
[[-0.1907593  -0.90837716]]
Izlazni sloj bias: 
[[0.64216428]]


In [384]:
# Z1 = 0
# Z2 = 1
# D = 1

X3 = np.expand_dims(X[2], 0)
y3 = y[2]

h = W1 @ X3.T + b1
H = 2/(1+np.exp(-h)) - 1
O = W2 @ H + b2

dW2 = -(y3-O)*H.T
db2 = -(y3-O)

dH = -(y3-O)*W2.T
dh = 0.5*(1-np.square(H))
dW1 = dH*dh*X3.T
db1 = dH*dh

W1 = W1 - 0.1*dW1
b1 = b1 - 0.1*db1
W2 = W2 - 0.1*dW2
b2 = b2 - 0.1*db2

print(f'Treći par:\nIzlaz: {O.item():.4f}\n')
print(f'Sakriveni sloj težine: \n{W1}\nSakriveni sloj bias: \n{b1}\n')
print(f'Izlazni sloj težine: \n{W2}\nIzlazni sloj bias: \n{b2}')

Treći par:
Izlaz: 0.1571

Sakriveni sloj težine: 
[[ 0.19941351  0.89941351]
 [-0.92974298  0.77025702]]
Sakriveni sloj bias: 
[[-0.30167364]
 [ 0.19627031]]

Izlazni sloj težine: 
[[-0.16600965 -0.86857007]]
Izlazni sloj bias: 
[[0.72645052]]


In [385]:
# Z1 = 1
# Z2 = 1
# D = 0

X4 = np.expand_dims(X[3], 0)
y4 = y[3]

h = W1 @ X4.T + b1
H = 2/(1+np.exp(-h)) - 1
O = W2 @ H + b2

dW2 = -(y4-O)*H.T
db2 = -(y4-O)

dH = -(y4-O)*W2.T
dh = 0.5*(1-np.square(H))
dW1 = dH*dh*X4.T

W1 = W1 - 0.1*dW1
b1 = b1 - 0.1*db1
W2 = W2 - 0.1*dW2
b2 = b2 - 0.1*db2

print(f'Četvrti par:\nIzlaz: {O.item():.4f}\n')
print(f'Sakriveni sloj težine: \n{W1}\nSakriveni sloj bias: \n{b1}\n')
print(f'Izlazni sloj težine: \n{W2}\nIzlazni sloj bias: \n{b2}')

Četvrti par:
Izlaz: 0.6476

Sakriveni sloj težine: 
[[ 0.20401791  0.90401791]
 [-0.90162799  0.79837201]]
Sakriveni sloj bias: 
[[-0.30901967]
 [ 0.16652733]]

Izlazni sloj težine: 
[[-0.19053641 -0.86976102]]
Izlazni sloj bias: 
[[0.66169007]]


In [386]:
W1, b1, W2, b2

(array([[ 0.20401791,  0.90401791],
        [-0.90162799,  0.79837201]]),
 array([[-0.30901967],
        [ 0.16652733]]),
 array([[-0.19053641, -0.86976102]]),
 array([[0.66169007]]))

In [387]:
# za usporedbu vrijednostima s prezentacije, jer su meni weights and bias malo drugaciji, vjerojatno zbog formata podataka

W1 = np.array([
    [0.2039, 0.8972],
    [-0.8749, 0.7979]
])

b1 = np.array([
    [-0.2971],
    [0.2239]
])

W2 = np.array([
    [-0.1899, -0.8706],
])

b2 = np.array([
    [0.6628]
])

In [388]:
def forward(X):
    h = W1 @ X.T + b1
    H = 2/(1+np.exp(-h)) - 1
    O = W2 @ H + b2

    return O

In [389]:
y_pred = forward(X).T
y_pred

array([[0.59374542],
       [0.94542187],
       [0.19772652],
       [0.52649214]])

In [390]:
MS = np.square(y_pred-y).sum() / len(y_pred)
RMS = np.sqrt(MS)
NRMS = RMS / np.std(y_pred)
NRMS

# u prezentaciji NRMS = 1,129765 ?

2.1277675727521252